### ISSUE TITLE
TimerTask not allowed to "touch" view for other thread

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#12]
```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:4176)
at android.view.ViewRootImpl.invalidateChild(ViewRootImpl.java:749)
at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:805)
at android.view.ViewGroup.invalidateChild(ViewGroup.java:4005)
at android.view.View.invalidate(View.java:8591)
at android.view.View.setFlags(View.java:6718)
at android.view.View.setVisibility(View.java:4632)
at com.ninetwozero.battlechat.activities.ChatActivity.toggleLoading(ChatActivity.java:374)
at com.ninetwozero.battlechat.activities.ChatActivity.access$0(ChatActivity.java:372)
at com.ninetwozero.battlechat.activities.ChatActivity$ReloadTask.onPreExecute(ChatActivity.java:248)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:561)
at android.os.AsyncTask.execute(AsyncTask.java:511)
at com.ninetwozero.battlechat.activities.ChatActivity.reload(ChatActivity.java:154)
at com.ninetwozero.battlechat.activities.ChatActivity.access$8(ChatActivity.java:151)
at com.ninetwozero.battlechat.activities.ChatActivity$2.run(ChatActivity.java:189)
at java.util.Timer$TimerImpl.run(Timer.java:284)
```

**Comment by karllindmark** [comment]
This has been addressed in #13.
