### ISSUE TITLE
java.lang.RuntimeException thrown in MainActivity::onCreate(Bundle)

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/Battle-Chat#44]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ninetwozero.battlechat/com.ninetwozero.battlechat.activities.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@412ed038: Unmarshalling unknown type code 6881390 at offset 1744
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1956)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1981)
at android.app.ActivityThread.access$600(ActivityThread.java:123)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1147)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4424)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@412ed038: Unmarshalling unknown type code 6881390 at offset 1744
at android.os.Parcel.readValue(Parcel.java:1921)
at android.os.Parcel.readListInternal(Parcel.java:2103)
at android.os.Parcel.readArrayList(Parcel.java:1544)
at android.os.Parcel.readValue(Parcel.java:1875)
at android.os.Parcel.readMapInternal(Parcel.java:2094)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getParcelable(Bundle.java:1158)
at android.app.Activity.onCreate(Activity.java:862)
at com.ninetwozero.battlechat.abstractions.AbstractListActivity.onCreate(AbstractListActivity.java:35)
at com.ninetwozero.battlechat.activities.MainActivity.onCreate(MainActivity.java:52)
at android.app.Activity.performCreate(Activity.java:4470)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1920)
... 11 more
```

**Comment by karllindmark** [comment]
Cannot be reproduced.
